CREATE TABLE "Question" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text,
  "amount_answer" int,
  "post_at" timestamp,
  "vote" int
);

CREATE TABLE "Answer" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text,
  "post_at" timestamp,
  "vote" int,
  "question_id" int
);

ALTER TABLE "Answer" ADD FOREIGN KEY ("question_id") REFERENCES "Question" ("id");
